Responsive
JosephColinP/home-bees pull request #3
Opened 2022-02-19 18:24 UTC by JosephColinP

## what

- deleted repeated code
- Crated a new class for all repeated atributes.
- Format the button tags and img tags

## why

- To have a cleaner code
- To have an understandable

## preview

![Widescreen](https://user-images.githubusercontent.com/89813296/154813754-2c7e2b97-1efa-496b-a345-7390f153e9c6.png)

## responsive

phone portrait

![cellphone-portrait](https://user-images.githubusercontent.com/89813296/154813795-e0721c80-d9a5-47c6-a501-b134b4d0883e.png)

phone landscape

![cellphone-landscape](https://user-images.githubusercontent.com/89813296/154813811-968c020e-31ec-409d-bbd3-9970b91c2fcf.png)

tablet portrait
![tablet-portrait](https://user-images.githubusercontent.com/89813296/154813824-dbc6b408-30fd-460a-90d0-2fa255c3dd67.png)

tablet landscape

![tablet-landscape](https://user-images.githubusercontent.com/89813296/154813839-d5d9c262-eea0-4139-a2b6-a9f50f5596b7.png)

## references
N/A

2022-02-21 23:24 UTC, semanticmx requested changes

2022-02-21 23:24 UTC, semanticmx commented on css/locations.css
> +.max-width {
este max-width se repite en dos archivos css. Lo que podemos hacer es agregar un 3er archivo CSS que se llame por ejemplo layout.css y meter los estilos en común que están en diferentes archivos para segiur reutilizando estilos.

2022-02-21 23:24 UTC, semanticmx commented on get-a-free-quote.html
> +        <a href="index.html" class="a-logo">
este va en dos líneas pero el primer atributo va en la línea d abajo

```
<a
  href="index.html"
  class="a-logo"
>
```

2022-02-21 23:24 UTC, semanticmx commented on get-a-free-quote.html
> +          <img class="logo"
Este atributo de class va abajo también

2022-03-02 19:21 UTC, semanticmx requested changes
mucho mejor!

2022-03-02 19:21 UTC, semanticmx commented on get-a-free-quote.html
> +          href="index.html">
esto no es muy común porque o se usa una imagen que incluya logo y logo2 o se hacen dos <a> uno para cada <img>

2022-03-03 00:05 UTC, JosephColinP commented on get-a-free-quote.html
> +          href="index.html">
Fue lo que se me ocurrió al momento hahaha. Es que quería cambiar el logo cuando se achique la pantalla para que pueda caber los links del navbar. Pero no sabía como hacer eso, y se me ocurrio poner dos logos, uno que su display esté en none y solo ocupe 1px. Y cuando llegue al tamaño deseado cambiar el display. No se como se haga eso de manera correcta

2022-03-03 01:28 UTC, semanticmx commented on get-a-free-quote.html
> +          href="index.html">
La idea es correcta, puedes tener una estructura similar a esto:

```
<nav>
 <a>
  <picture>.logo</picture>
 </a>
 <a class="desktop">
  <picture>.logo-desktop</picture>
 </a>
 <a>
  <picture>.menu de hamburguesa</picture>
 </a>
 <ul class="desktop">
  <li>.menu item</li>
 </ul>
</nav>

```

donde la clase `desktop` es la que muestra la lista del menú en resoluciones que no sean la móvil y en ese caso oculta los otros elementos.

Pero en ese caso el link de las imágenes va 1 a 1, en caso de que el link en móvil te lleve a otro lado por ejemplo.

2022-05-24 14:40 UTC, merged